Update workflow and Makefile

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -17,12 +17,12 @@ jobs:
         run: make all
 
       - name: Copy out example bat
-        run: cp examples/go-miner-*.bat .
+        run: cp examples/noso-*.bat .
 
       - uses: actions/upload-artifact@v2
         with:
           path: |
-            bin/go-miner-*
+            bin/noso-*
             README.md
 
   test-linux:
@@ -32,15 +32,23 @@ jobs:
     steps:
       - uses: actions/download-artifact@v2
         name: Download Artifacts
-      - name: Run basic commands
+      - name: Move artifacts
         run: |
           mv artifact/bin .
-          chmod a+x bin/go-miner-linux-386
-          bin/go-miner-linux-386 -h
-          bin/go-miner-linux-386 -version
-          chmod a+x bin/go-miner-linux-amd64
-          bin/go-miner-linux-amd64 -h
-          bin/go-miner-linux-amd64 -version
+      - name: Run basic commands - i386
+        run: |
+          chmod a+x bin/noso-linux-386
+          bin/noso-linux-386 -h
+          bin/noso-linux-386 version
+          bin/noso-linux-386 benchmark
+          bin/noso-linux-386 mine -h
+      - name: Run basic commands - x86_64
+        run: |
+          chmod a+x bin/noso-linux-amd64
+          bin/noso-linux-amd64 -h
+          bin/noso-linux-amd64 version
+          bin/noso-linux-amd64 benchmark
+          bin/noso-linux-amd64 mine -h
 
   test-windows:
     name: Test Windows
@@ -54,12 +62,16 @@ jobs:
           mv artifact/bin .
       - name: Run basic commands - 64 Bit
         run: |
-          bin/go-miner-windows-amd64 -h
-          bin/go-miner-windows-amd64 -version
+          bin/noso-windows-amd64 -h
+          bin/noso-windows-amd64 version
+          bin/noso-windows-amd64 bencmark
+          bin/noso-windows-amd64 mine -h
       - name: Run basic commands - 32 Bit
         run: |
-          bin/go-miner-windows-386 -h
-          bin/go-miner-windows-386 -version
+          bin/noso-windows-386 -h
+          bin/noso-windows-386 version
+          bin/noso-windows-386 benchmark
+          bin/noso-windows-386 mine -h
 
   test-macos:
     name: Test Mac OS
@@ -73,10 +85,13 @@ jobs:
           mv artifact/bin .
       - name: Run basic commands
         run: |
-          chmod a+x bin/go-miner-darwin-amd64
-          bin/go-miner-darwin-amd64 -h
-          bin/go-miner-darwin-amd64 -version
+          chmod a+x bin/noso-darwin-amd64
+          bin/noso-darwin-amd64 -h
+          bin/noso-darwin-amd64 version
+          bin/noso-darwin-amd64 benchmark
+          bin/noso-darwin-amd64 mine -h
 
+  # TODO: See if we can use qemu to actually test these binaries
   test-arm:
     name: Test ARM
     runs-on: ubuntu-latest
@@ -89,8 +104,8 @@ jobs:
           mv artifact/bin .
       - name: Run basic commands
         run: |
-          sh -c 'if test -f "bin/go-miner-linux-arm"; then echo "ARM binary found"; else echo "ARM binary not found" && exit 1; fi'
-          sh -c 'if test -f "bin/go-miner-linux-arm64"; then echo "ARM64 binary found"; else echo "ARM64 binary not found" && exit 1; fi'
+          sh -c 'if test -f "bin/noso-linux-arm"; then echo "ARM binary found"; else echo "ARM binary not found" && exit 1; fi'
+          sh -c 'if test -f "bin/noso-linux-arm64"; then echo "ARM64 binary found"; else echo "ARM64 binary not found" && exit 1; fi'
 
   package-release:
     if: contains(github.ref, '/tags/v')
@@ -111,7 +126,7 @@ jobs:
         uses: softprops/action-gh-release@v1
         with:
           files: |
-            packages/go-miner*.zip
-            packages/go-miner*.tgz
+            packages/noso*.zip
+            packages/noso*.tgz
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
