Update workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -21,9 +21,8 @@ jobs:
 
       - uses: actions/upload-artifact@v2
         with:
-          name: bin
           path: |
-            go-miner-*
+            bin/go-miner-*
             README.md
 
   test-linux:
@@ -35,9 +34,13 @@ jobs:
         name: Download Artifacts
       - name: Run basic commands
         run: |
-          chmod a+x bin/go-miner-linux
-          bin/go-miner-linux -h
-          bin/go-miner-linux -version
+          mv artifact/bin .
+          chmod a+x bin/go-miner-linux-386
+          bin/go-miner-linux-386 -h
+          bin/go-miner-linux-386 -version
+          chmod a+x bin/go-miner-linux-amd64
+          bin/go-miner-linux-amd64 -h
+          bin/go-miner-linux-amd64 -version
 
   test-windows:
     name: Test Windows
@@ -46,14 +49,17 @@ jobs:
     steps:
       - uses: actions/download-artifact@v2
         name: Download Artifacts
+      - name: Move bins
+        run: |
+          mv artifact/bin .
       - name: Run basic commands - 64 Bit
         run: |
-          bin/go-miner-64.exe -h
-          bin/go-miner-64.exe -version
+          bin/go-miner-windows-amd64 -h
+          bin/go-miner-windows-amd64 -version
       - name: Run basic commands - 32 Bit
         run: |
-          bin/go-miner-32.exe -h
-          bin/go-miner-32.exe -version
+          bin/go-miner-windows-386 -h
+          bin/go-miner-windows-386 -version
 
   test-macos:
     name: Test Mac OS
@@ -62,11 +68,14 @@ jobs:
     steps:
       - uses: actions/download-artifact@v2
         name: Download Artifacts
+      - name: Move bins
+        run: |
+          mv artifact/bin .
       - name: Run basic commands
         run: |
-          chmod a+x bin/go-miner-macos
-          bin/go-miner-macos -h
-          bin/go-miner-macos -version
+          chmod a+x bin/go-miner-darwin-amd64
+          bin/go-miner-darwin-amd64 -h
+          bin/go-miner-darwin-amd64 -version
 
   test-arm:
     name: Test ARM
@@ -75,14 +84,17 @@ jobs:
     steps:
       - uses: actions/download-artifact@v2
         name: Download Artifacts
+      - name: Move bins
+        run: |
+          mv artifact/bin .
       - name: Run basic commands
         run: |
-          sh -c 'if test -f "bin/go-miner-arm"; then echo "ARM binary found"; else echo "ARM binary not found" && exit 1; fi'
-          sh -c 'if test -f "bin/go-miner-arm64"; then echo "ARM64 binary found"; else echo "ARM64 binary not found" && exit 1; fi'
+          sh -c 'if test -f "bin/go-miner-linux-arm"; then echo "ARM binary found"; else echo "ARM binary not found" && exit 1; fi'
+          sh -c 'if test -f "bin/go-miner-linux-arm64"; then echo "ARM64 binary found"; else echo "ARM64 binary not found" && exit 1; fi'
 
-  package-linux-i386:
+  package-release:
     if: contains(github.ref, '/tags/v')
-    name: Package linux i386
+    name: Package and Upload
     runs-on: ubuntu-latest
     needs: [build, test-linux, test-windows, test-macos, test-arm]
     steps:
@@ -90,12 +102,16 @@ jobs:
         uses: actions/checkout@master
       - uses: actions/download-artifact@v2
         name: Download Artifacts
+      - name: Move bins
+        run: |
+          mv artifact/bin .
       - name: Package
-        run: make zip
+        run: make packages
       - name: Upload Release
         uses: softprops/action-gh-release@v1
         with:
           files: |
-            go-miner*.zip
+            packages/go-miner*.zip
+            packages/go-miner*.tgz
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
